```python
#Written by Alex Szepes - 9/5/2022

from datetime import date
import os

#Arugment for the create_spraylist function to get the company name
# NOT LONGER USED BUT MIGHT BE USEFUL LATER
#def get_companyName():
#    return input("Enter company name: ")

def create_spraylist(companyName):

    print("\nCreating wordlist...")
    #Add new passwords in here. No need to worry about case.
    passwords = (companyName,)
    current_year = date.today().year

    with open("temp.txt", 'w') as f:
    
        #Formatting for each word in the list
        for x in passwords:
            ##########################
            ##Uppercase first letter##
            ##########################
            f.write(x.capitalize() + "\n")
            f.write(x.capitalize() + "1\n")
            f.write(x.capitalize() + "!\n")
            f.write(x.capitalize() + "123\n")
            f.write(x.capitalize() + "123!\n")
            f.write(x.capitalize() + str(current_year) + "\n")
            f.write(x.capitalize() + str(current_year -1) + "\n")
            f.write(x.capitalize() + str(current_year -2) + "\n")
            f.write(x.capitalize() + str(current_year) + "!\n")
            f.write(x.capitalize() + str(current_year -1) + "!\n")
            f.write(x.capitalize() + str(current_year -2) + "!\n")
            f.write(x.capitalize() + str(current_year -2000) + "\n")
            f.write(x.capitalize() + str(current_year -2001) + "\n")
            f.write(x.capitalize() + str(current_year -2002) + "\n")
            f.write(x.capitalize() + str(current_year -2000) + "!\n")
            f.write(x.capitalize() + str(current_year -2001) + "!\n")
            f.write(x.capitalize() + str(current_year -2002) + "!\n")
            #Replace the letter "a" with "4"
            f.write(x.capitalize().replace("a","4") + "\n")
            f.write(x.capitalize().replace("a","4") + "1\n")
            f.write(x.capitalize().replace("a","4") + "!\n")
            f.write(x.capitalize().replace("a","4") + "123\n")
            f.write(x.capitalize().replace("a","4") + "123!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("a","4") + str(current_year -2002) + "!\n")
            #Replace the letter "a" with "@"
            f.write(x.capitalize().replace("a","@") + "\n")
            f.write(x.capitalize().replace("a","@") + "1\n")
            f.write(x.capitalize().replace("a","@") + "!\n")
            f.write(x.capitalize().replace("a","@") + "123\n")
            f.write(x.capitalize().replace("a","@") + "123!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("a","@") + str(current_year -2002) + "!\n")
            #Replace the letter "s" with 5
            f.write(x.capitalize().replace("s","5") + "\n")
            f.write(x.capitalize().replace("s","5") + "1\n")
            f.write(x.capitalize().replace("s","5") + "!\n")
            f.write(x.capitalize().replace("s","5") + "123\n")
            f.write(x.capitalize().replace("s","5") + "123!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("s","5") + str(current_year -2002) + "!\n")
            #Replace the letter "i" with 1
            f.write(x.capitalize().replace("i","1") + "\n")
            f.write(x.capitalize().replace("i","1") + "1\n")
            f.write(x.capitalize().replace("i","1") + "!\n")
            f.write(x.capitalize().replace("i","1") + "123\n")
            f.write(x.capitalize().replace("i","1") + "123!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("i","1") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3
            f.write(x.capitalize().replace("e","3") + "\n")
            f.write(x.capitalize().replace("e","3") + "1\n")
            f.write(x.capitalize().replace("e","3") + "!\n")
            f.write(x.capitalize().replace("e","3") + "123\n")
            f.write(x.capitalize().replace("e","3") + "123!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("e","3") + str(current_year -2002) + "!\n")
            #Replace the letter "t" with 7
            f.write(x.capitalize().replace("t","7") + "\n")
            f.write(x.capitalize().replace("t","7") + "1\n")
            f.write(x.capitalize().replace("t","7") + "!\n")
            f.write(x.capitalize().replace("t","7") + "123\n")
            f.write(x.capitalize().replace("t","7") + "123!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("t","7") + str(current_year -2002) + "!\n")
            #Replace the letter "o" with 
            f.write(x.capitalize().replace("o","0") + "\n")
            f.write(x.capitalize().replace("o","0") + "1\n")
            f.write(x.capitalize().replace("o","0") + "!\n")
            f.write(x.capitalize().replace("o","0") + "123\n")
            f.write(x.capitalize().replace("o","0") + "123!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("o","0") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3, "a" with "@", "i" with "1", "s" with "5", "o" with "0"
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "1\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3, "a" with "4", "i" with "1", "s" with "5", "o" with "0"
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "1\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.capitalize().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "!\n")
            ##########################
            ##Lowercase first letter##
            ##########################
            f.write(x.lower() + "\n")
            f.write(x.lower() + "1\n")
            f.write(x.lower() + "!\n")
            f.write(x.lower() + "123\n")
            f.write(x.lower() + "123!\n")
            f.write(x.lower() + str(current_year) + "\n")
            f.write(x.lower() + str(current_year -1) + "\n")
            f.write(x.lower() + str(current_year -2) + "\n")
            f.write(x.lower() + str(current_year) + "!\n")
            f.write(x.lower() + str(current_year -1) + "!\n")
            f.write(x.lower() + str(current_year -2) + "!\n")
            f.write(x.lower() + str(current_year -2000) + "\n")
            f.write(x.lower() + str(current_year -2001) + "\n")
            f.write(x.lower() + str(current_year -2002) + "\n")
            f.write(x.lower() + str(current_year -2000) + "!\n")
            f.write(x.lower() + str(current_year -2001) + "!\n")
            f.write(x.lower() + str(current_year -2002) + "!\n")
            #Replace the letter "a" with "4"
            f.write(x.lower().replace("a","4") + "\n")
            f.write(x.lower().replace("a","4") + "1\n")
            f.write(x.lower().replace("a","4") + "!\n")
            f.write(x.lower().replace("a","4") + "123\n")
            f.write(x.lower().replace("a","4") + "123!\n")
            f.write(x.lower().replace("a","4") + str(current_year) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -1) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -2) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("a","4") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("a","4") + str(current_year -2002) + "!\n")
            #Replace the letter "a" with "@"
            f.write(x.lower().replace("a","@") + "\n")
            f.write(x.lower().replace("a","@") + "1\n")
            f.write(x.lower().replace("a","@") + "!\n")
            f.write(x.lower().replace("a","@") + "123\n")
            f.write(x.lower().replace("a","@") + "123!\n")
            f.write(x.lower().replace("a","@") + str(current_year) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -1) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -2) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("a","@") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("a","@") + str(current_year -2002) + "!\n")
            #Replace the letter "s" with "5"
            f.write(x.lower().replace("s","5") + "\n")
            f.write(x.lower().replace("s","5") + "1\n")
            f.write(x.lower().replace("s","5") + "!\n")
            f.write(x.lower().replace("s","5") + "123\n")
            f.write(x.lower().replace("s","5") + "123!\n")
            f.write(x.lower().replace("s","5") + str(current_year) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -1) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -2) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("s","5") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("s","5") + str(current_year -2002) + "!\n")
            #Replace the letter "i" with "I"
            f.write(x.lower().replace("i","1") + "\n")
            f.write(x.lower().replace("i","1") + "1\n")
            f.write(x.lower().replace("i","1") + "!\n")
            f.write(x.lower().replace("i","1") + "123\n")
            f.write(x.lower().replace("i","1") + "123!\n")
            f.write(x.lower().replace("i","1") + str(current_year) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -1) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -2) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("i","1") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("i","1") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with "3"
            f.write(x.lower().replace("e","3") + "\n")
            f.write(x.lower().replace("e","3") + "1\n")
            f.write(x.lower().replace("e","3") + "!\n")
            f.write(x.lower().replace("e","3") + "123\n")
            f.write(x.lower().replace("e","3") + "123!\n")
            f.write(x.lower().replace("e","3") + str(current_year) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -1) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -2) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("e","3") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("e","3") + str(current_year -2002) + "!\n")
            #Replace the letter "t" with "7"
            f.write(x.lower().replace("t","7") + "\n")
            f.write(x.lower().replace("t","7") + "1\n")
            f.write(x.lower().replace("t","7") + "!\n")
            f.write(x.lower().replace("t","7") + "123\n")
            f.write(x.lower().replace("t","7") + "123!\n")
            f.write(x.lower().replace("t","7") + str(current_year) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -1) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -2) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("t","7") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("t","7") + str(current_year -2002) + "!\n")
            #Replace the letter "o" with "0"
            f.write(x.lower().replace("o","0") + "\n")
            f.write(x.lower().replace("o","0") + "1\n")
            f.write(x.lower().replace("o","0") + "!\n")
            f.write(x.lower().replace("o","0") + "123\n")
            f.write(x.lower().replace("o","0") + "123!\n")
            f.write(x.lower().replace("o","0") + str(current_year) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -1) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -2) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("o","0") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3, "a" with "@", "i" with "1", "s" with "5", "t" with "7", "o" with "0"
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "1\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","@").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "!\n")
            #Replace the letter "e" with 3, "a" with "4", "i" with "1", "s" with "5", "t" with "7", "o" with "0"
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "1\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + "123!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -1) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2000) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2001) + "!\n")
            f.write(x.lower().replace("e","3").replace("a","4").replace("i","1").replace("s","5").replace("t","7").replace("o","0") + str(current_year -2002) + "!\n")
    f.close()

#Called from main after the temporary list has been created. Duplicates are created when there are no letters to replace so the word gets created anyway without any modifications
#This reads the temp.txt file and removes the duplicates then saves the new file with the company name input by the user.
def remove_duplicates(inFileName,companyName):
    print("Removing duplicates...")
    lines_seen = set()#holds lines already seen
    outfile = open(companyName + ".txt", "w")
    for line in open(inFileName, "r"):
        if line not in lines_seen:#not a duplicate
            outfile.write(line)
            lines_seen.add(line)
    outfile.close()

if __name__ == '__main__':
    #Create password spray file with the company name as input
    companyName = input("\nEnter company name: ")
    create_spraylist(companyName)
    
    #Remove any Duplicates
    remove_duplicates("temp.txt",companyName)
    
    #Delete temp file
    print("Deleting temporary file...")
    os.remove("temp.txt")
    
    print("\nWordlist successfully created in: " + os.path.abspath(os.getcwd()) + "\\" + companyName + ".txt\n")
```
